### ISSUE TITLE
Is there any tutorial to understand this repository

### ISSUE THREAD

**Issue by beratersari** [kukuruza/CADillac#3]
`python3 render/MakePatches.py   -o $PATCHDIR/scenes.db   --num_sessions 10 --num_per_session 3 --num_occluding 1 2 3 4 5 --mode PARALLEL   --clause_main 'WHERE error IS NULL AND dims_L < 10'   --cad_db_path $CADILLAC_DATA_PATH/CAD/collections_v1.db
Traceback (most recent call last):
  File "render/MakePatches.py", line 17, in <module>
    sys.path.insert(0, op.join(os.getenv('SHUFFLER_PATH'), 'lib'))
  File "/usr/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
`

I runned the first script in render folder. However, it gives error. The repository is too complex for me. Is there any tutorial for this repository?

**Comment by beratersari** [comment]
Also where is the db files, I can not see in the dataset zip. 

![image](https://user-images.githubusercontent.com/56562278/203924241-150bb42a-676e-4273-b551-77e6b130c29a.png)

Its content is shown above.
